server:
  port: 8080

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vsouzx/Microservicos-Clone-Twitter-Repository
          default-label: main
