name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: vtsoliveira2001@gmail.com
          password: Vs368797@

      - name: Build and push Docker image
        run: |
          docker build -t my-image-name .
          docker tag my-image-name vsouzx/twitter-configserver:v${VER}
          docker push vsouzx/my-image-name:v${VER}
