name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: vtsoliveira2001@gmail.com
          password: Vs368797@

      - name: Build and push Docker image
        run: |
          docker build -t vsouzx/twitter-configserver --file .\configserver\Dockerfile .
          docker push vsouzx/twitter-configserver
