name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vtsoliveira2001@gmail.com
          password: Vs368797@

      - name: Build and push register app
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./configserver/Dockerfile
          tags: vsouzx/twitter-configserver:1.0.2