name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          echo "Vs368797@" | docker login -u "vtsoliveira2001@gmail.com" --password-stdin
          docker build -t vsouzx/twitter-configserver:1.0.2 --file Microservicos-Clone-Twitter/configserver/Dockerfile .
          docker push vsouzx/twitter-configserver:1.0.2